-- Create contacts table
create table public.contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  subject text not null,
  message text not null
);

-- Set up Row Level Security (RLS)
alter table public.contacts enable row level security;

-- Create a policy that allows inserting data
create policy "Allow public to insert contacts"
  on public.contacts for insert
  with check (true);

-- Add an index on email for faster lookups
create index contacts_email_idx on public.contacts(email); 